# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

# This script processes daily and official releases (alpha/beta/rc and final)
# To trigger an official release, add a commit tagged in the form "luxcorerender_v*"
# The "version_string" after the "_" in the tag is used in following steps
# to generate binary names like "luxcorerender-<version_string>-<platform>-..."
# One, and only one, tag in the form "luxcorerender_v*" is needed, 
# otherwise the official release build aborts.

trigger:
  branches:
    include:
    - '*'


jobs:
- job: DetectBuildType
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-18.04'
    
  steps:
  - script: ./scripts/azurepipeline/detect-build-type.sh
    displayName: Detecting release type (daily, alpha, beta or final)
    name: setvarStep
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: LuxCore
    displayName: 'Upload github_release_title'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')

#==============================================================================
# Windows binaries
#==============================================================================
- job: LuxCoreRenderWindows
  dependsOn: DetectBuildType
  condition: succeeded()
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    version_string: $[ dependencies.DetectBuildType.outputs['setvarStep.version_string'] ]

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'
  - script: ./scripts/azurepipeline/windows/deps-setup.cmd
    displayName: Getting required deps
  - template: ./scripts/azurepipeline/windows/windows_jobs.yml
    parameters:
      build_script: './scripts/azurepipeline/windows/build.cmd /cmake-only /no-ocl'
      post_script: './scripts/azurepipeline/windows/post-build.cmd /no-ocl'
      ocl_text: 'OpenCL disabled'
      minimalargs: '/target:pyluxcore,pyluxcoretools,luxcoreui'
  - template: ./scripts/azurepipeline/windows/windows_jobs.yml
    parameters:
      build_script: './scripts/azurepipeline/windows/build.cmd /cmake-only'
      post_script: './scripts/azurepipeline/windows/post-build.cmd'
      ocl_text: 'OpenCL enabled'
      minimalargs: '/target:pyluxcore,pyluxcoretools,luxcoreui'
  - script: './scripts/azurepipeline/windows/test.cmd'
    displayName: Testing LuxCore
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: LuxCore
    displayName: 'Upload luxcorerender-<version>-win64.zip'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
